local E, L, V, P, G = unpack(ElvUI);
local EP = LibStub("LibElvUIPlugin-1.0")
local addon = ...

local M = E:NewModule("MyProfile")

local function myUI()
	--Сохраняем критические настройки перед очисткой таблиц
	local layout = E.db.layoutSet
	local install = E.private["install_complete"]
	--Очистка и перезаполнение профиля
	table.wipe(E.db)
	E:CopyTable(E.db, P)
	--Очистка и перезаполнение приватных настроек
	table.wipe(E.private)
	E:CopyTable(E.private, V)
	if E.db['movers'] then table.wipe(E.db['movers']) else E.db['movers'] = {} end
	
	--Ваши настройки 
	E.db["databars"]["artifact"]["enable"] = false
	E.db["databars"]["reputation"]["enable"] = true
	E.db["databars"]["reputation"]["font"] = "big_noodle_titling"
	E.db["databars"]["reputation"]["width"] = 7
	E.db["databars"]["reputation"]["reverseFill"] = true
	E.db["databars"]["experience"]["font"] = "big_noodle_titling"
	E.db["databars"]["experience"]["orientation"] = "HORIZONTAL"
	E.db["databars"]["experience"]["height"] = 5
	E.db["databars"]["experience"]["enable"] = false
	E.db["databars"]["experience"]["width"] = 2134
	E.db["databars"]["honor"]["enable"] = false
	E.db["currentTutorial"] = 9
	E.db["general"]["totems"]["sortDirection"] = "DESCENDING"
	E.db["general"]["totems"]["growthDirection"] = "HORIZONTAL"
	E.db["general"]["totems"]["size"] = 52
	E.db["general"]["totems"]["spacing"] = 1
	E.db["general"]["afk"] = false
	E.db["general"]["autoRepair"] = "GUILD"
	E.db["general"]["minimap"]["locationFontOutline"] = "NONE"
	E.db["general"]["minimap"]["locationFont"] = "big_noodle_titling"
	E.db["general"]["minimap"]["icons"]["difficulty"]["scale"] = 0.9
	E.db["general"]["minimap"]["icons"]["difficulty"]["position"] = "TOPRIGHT"
	E.db["general"]["minimap"]["icons"]["difficulty"]["xOffset"] = -1
	E.db["general"]["minimap"]["icons"]["difficulty"]["yOffset"] = -50
	E.db["general"]["minimap"]["icons"]["ticket"]["yOffset"] = -39
	E.db["general"]["minimap"]["icons"]["mail"]["yOffset"] = -32
	E.db["general"]["minimap"]["icons"]["classHall"]["scale"] = 0.7
	E.db["general"]["minimap"]["icons"]["classHall"]["yOffset"] = -15
	E.db["general"]["minimap"]["icons"]["classHall"]["position"] = "TOPRIGHT"
	E.db["general"]["minimap"]["icons"]["vehicleLeave"]["yOffset"] = 10
	E.db["general"]["bottomPanel"] = false
	E.db["general"]["backdropfadecolor"]["a"] = 0.8500000089407
	E.db["general"]["backdropfadecolor"]["r"] = 0.090196078431373
	E.db["general"]["backdropfadecolor"]["g"] = 0.090196078431373
	E.db["general"]["backdropfadecolor"]["b"] = 0.090196078431373
	E.db["general"]["valuecolor"]["a"] = 1
	E.db["general"]["valuecolor"]["r"] = 0.09
	E.db["general"]["valuecolor"]["g"] = 0.513
	E.db["general"]["valuecolor"]["b"] = 0.819
	E.db["general"]["threat"]["enable"] = false
	E.db["general"]["stickyFrames"] = false
	E.db["general"]["backdropcolor"]["r"] = 0.10196078431373
	E.db["general"]["backdropcolor"]["g"] = 0.10196078431373
	E.db["general"]["backdropcolor"]["b"] = 0.10196078431373
	E.db["general"]["topPanel"] = false
	E.db["general"]["bordercolor"]["r"] = 0
	E.db["general"]["bordercolor"]["g"] = 0
	E.db["general"]["bordercolor"]["b"] = 0
	E.db["general"]["font"] = "Continuum Medium"
	E.db["general"]["vendorGrays"] = true
	E.db["bags"]["junkIcon"] = true
	E.db["bags"]["countFont"] = "Continuum Medium"
	E.db["bags"]["itemLevelFont"] = "Continuum Medium"
	E.db["bags"]["xOffset"] = -22
	E.db["bags"]["yOffset"] = 256
	E.db["bags"]["itemLevelFontSize"] = 12
	E.db["bags"]["moneyFormat"] = "CONDENSED"
	E.db["bags"]["countFontSize"] = 12
	E.db["hideTutorial"] = true
	E.db["CNB"]["install_version"] = "1.61"
	E.db["CNB"]["general"]["chatbubblecolor"]["r"] = 0.43137254901961
	E.db["CNB"]["general"]["chatbubblecolor"]["g"] = 0.74901960784314
	E.db["CNB"]["general"]["chatbubblecolor"]["b"] = 0.45882352941177
	E.db["CNB"]["chat"]["chatDataSeparator"] = "HIDEBOTH"
	E.db["CNB"]["chat"]["editboxFont"] = "Continuum Medium"
	E.db["CNB"]["chat"]["bracketSelectedTab"] = false
	E.db["CNB"]["chat"]["chatTabSeparator"] = "HIDEBOTH"
	E.db["CNB"]["datatexts"]["rightChatTabDatatextPanel"] = false
	E.db["CNB"]["datatexts"]["bottomDatatextPanel"] = false
	E.db["CNB"]["datatexts"]["panels"]["ChatTab_Datatext_Panel"]["right"] = ""
	E.db["CNB"]["datatexts"]["panels"]["ChatTab_Datatext_Panel"]["left"] = ""
	E.db["CNB"]["datatexts"]["panels"]["ChatTab_Datatext_Panel"]["middle"] = ""
	E.db["CNB"]["datatexts"]["panels"]["Bottom_Datatext_Panel"]["right"] = ""
	E.db["CNB"]["datatexts"]["panels"]["Bottom_Datatext_Panel"]["left"] = ""
	E.db["CNB"]["datatexts"]["panels"]["Bottom_Datatext_Panel"]["middle"] = ""
	E.db["CNB"]["datatexts"]["invisibleChatDataPanel"] = false
	E.db["CNB"]["unitframes"]["auras"]["decimalThreshold"] = 1
	E.db["layoutSet"] = "healer"
	E.db["thinBorderColorSet"] = true
	E.db["bagSortIgnoreItemsReset"] = true
	E.db["movers"]["ElvUF_FocusCastbarMover"] = "BOTTOMLEFT,ElvUIParent,BOTTOMLEFT,566,390"
	E.db["movers"]["ElvUF_PlayerCastbarMover"] = "BOTTOM,ElvUIParent,BOTTOM,0,384"
	E.db["movers"]["ElvUF_RaidMover"] = "TOPLEFT,ElvUIParent,BOTTOMLEFT,813,280"
	E.db["movers"]["ElvUF_FocusTargetMover"] = "BOTTOMLEFT,ElvUIParent,BOTTOMLEFT,430,405"
	E.db["movers"]["GMMover"] = "TOPLEFT,ElvUIParent,TOPLEFT,305,0"
	E.db["movers"]["BuffsMover"] = "TOPRIGHT,ElvUIParent,TOPRIGHT,-187,-4"
	E.db["movers"]["ElvUF_PetTargetMover"] = "BOTTOMLEFT,ElvUIParent,BOTTOMLEFT,434,339"
	E.db["movers"]["LootFrameMover"] = "TOP,ElvUIParent,TOP,18,-269"
	E.db["movers"]["ZoneAbility"] = "BOTTOM,ElvUIParent,BOTTOM,0,480"
	E.db["movers"]["ElvUF_RaidpetMover"] = "TOPLEFT,ElvUIParent,BOTTOMLEFT,1327,458"
	E.db["movers"]["ElvUF_FocusMover"] = "BOTTOMLEFT,ElvUIParent,BOTTOMLEFT,566,408"
	E.db["movers"]["ElvUF_TargetTargetMover"] = "BOTTOMRIGHT,ElvUIParent,BOTTOMRIGHT,-428,341"
	E.db["movers"]["ClassBarMover"] = "BOTTOM,ElvUIParent,BOTTOM,-10,278"
	E.db["movers"]["MicrobarMover"] = "BOTTOMLEFT,ElvUIParent,BOTTOMLEFT,0,197"
	E.db["movers"]["PlayerPowerBarMover"] = "BOTTOM,ElvUIParent,BOTTOM,0,283"
	E.db["movers"]["VehicleSeatMover"] = "TOPLEFT,ElvUIParent,TOPLEFT,513,0"
	E.db["movers"]["BossButton"] = "BOTTOM,ElvUIParent,BOTTOM,0,480"
	E.db["movers"]["ExperienceBarMover"] = "BOTTOM,ElvUIParent,BOTTOM,0,0"
	E.db["movers"]["RightChatMover"] = "BOTTOMRIGHT,ElvUIParent,BOTTOMRIGHT,-166,333"
	E.db["movers"]["ElvUIBankMover"] = "BOTTOMLEFT,ElvUIParent,BOTTOMLEFT,5,186"
	E.db["movers"]["ElvUIBagMover"] = "BOTTOMRIGHT,ElvUIParent,BOTTOMRIGHT,-43,238"
	E.db["movers"]["LossControlMover"] = "TOP,ElvUIParent,TOP,6,-483"
	E.db["movers"]["ElvUF_Raid40Mover"] = "TOPLEFT,ElvUIParent,BOTTOMLEFT,813,280"
	E.db["movers"]["TotemBarMover"] = "BOTTOM,ElvUIParent,BOTTOM,103,450"
	E.db["movers"]["ElvUF_TargetMover"] = "BOTTOMRIGHT,ElvUIParent,BOTTOMRIGHT,-564,341"
	E.db["movers"]["ElvAB_1"] = "BOTTOM,ElvUIParent,BOTTOM,0,298"
	E.db["movers"]["ElvAB_2"] = "BOTTOMRIGHT,ElvUIParent,BOTTOMRIGHT,0,205"
	E.db["movers"]["ElvAB_4"] = "BOTTOMRIGHT,ElvUIParent,BOTTOMRIGHT,-180,27"
	E.db["movers"]["DTB2_1_Mover"] = "TOP,ElvUIParent,TOP,0,1"
	E.db["movers"]["TalkingHeadFrameMover"] = "TOP,ElvUIParent,TOP,-15,0"
	E.db["movers"]["ElvUF_TargetCastbarMover"] = "BOTTOMRIGHT,ElvUIParent,BOTTOMRIGHT,-564,323"
	E.db["movers"]["AltPowerBarMover"] = "TOP,ElvUIParent,TOP,-1,-44"
	E.db["movers"]["ElvAB_3"] = "BOTTOM,ElvUIParent,BOTTOM,0,333"
	E.db["movers"]["ReputationBarMover"] = "TOPLEFT,ElvUIParent,TOPLEFT,0,0"
	E.db["movers"]["ArtifactBarMover"] = "BOTTOMLEFT,ElvUIParent,BOTTOMLEFT,3,406"
	E.db["movers"]["ElvAB_5"] = "BOTTOM,ElvUIParent,BOTTOM,-230,301"
	E.db["movers"]["PetAB"] = "BOTTOMRIGHT,ElvUIParent,BOTTOMRIGHT,-4,245"
	E.db["movers"]["ObjectiveFrameMover"] = "TOPLEFT,ElvUIParent,TOPLEFT,106,-7"
	E.db["movers"]["BNETMover"] = "TOPRIGHT,ElvUIParent,TOPRIGHT,0,-457"
	E.db["movers"]["ShiftAB"] = "TOPLEFT,ElvUIParent,BOTTOMLEFT,856,426"
	E.db["movers"]["ElvUF_BodyGuardMover"] = "TOP,ElvUIParent,TOP,0,-516"
	E.db["movers"]["HonorBarMover"] = "BOTTOMRIGHT,ElvUIParent,BOTTOMRIGHT,-416,0"
	E.db["movers"]["ElvAB_6"] = "BOTTOM,ElvUIParent,BOTTOM,230,299"
	E.db["movers"]["TooltipMover"] = "BOTTOMRIGHT,ElvUIParent,BOTTOMRIGHT,-229,31"
	E.db["movers"]["ElvUF_PetMover"] = "BOTTOMLEFT,ElvUIParent,BOTTOMLEFT,568,340"
	E.db["movers"]["BossHeaderMover"] = "TOPRIGHT,ElvUIParent,TOPRIGHT,-282,-423"
	E.db["movers"]["ElvUF_PlayerMover"] = "BOTTOM,ElvUIParent,BOTTOM,0,368"
	E.db["movers"]["dataText1Mover"] = "TOP,ElvUIParent,TOP,18,1"
	E.db["movers"]["ElvUF_PartyMover"] = "TOPLEFT,ElvUIParent,BOTTOMLEFT,813,280"
	E.db["movers"]["AlertFrameMover"] = "BOTTOMLEFT,ElvUIParent,BOTTOMLEFT,546,434"
	E.db["movers"]["DebuffsMover"] = "TOPRIGHT,ElvUIParent,TOPRIGHT,-188,-153"
	E.db["movers"]["MinimapMover"] = "BOTTOMRIGHT,ElvUIParent,BOTTOMRIGHT,-2,28"
	E.db["gridSize"] = 32
	E.db["tooltip"]["font"] = "Continuum Medium"
	E.db["tooltip"]["fontSize"] = 12
	E.db["tooltip"]["healthBar"]["height"] = 1
	E.db["tooltip"]["healthBar"]["font"] = "Continuum Medium"
	E.db["tooltip"]["healthBar"]["text"] = true
	E.db["tooltip"]["playerTitles"] = false
	E.db["tooltip"]["talentInfo"] = true
	E.db["tooltip"]["targetInfo"] = true
	E.db["UFP"]["unitframes"]["use_Backdrope_texture"] = false
	E.db["UFP"]["unitframes"]["health"]["colors"]["transparent_backdrope"] = 0.8
	E.db["UFP"]["unitframes"]["health"]["colors"]["transparent_statusbar"] = 0.8
	E.db["UFP"]["unitframes"]["health"]["texture"]["use_texture"] = true
	E.db["UFP"]["unitframes"]["health"]["texture"]["use_Backdrope_texture"] = true
	E.db["UFP"]["unitframes"]["health"]["texture"]["backdrope_texture"] = "fer34"
	E.db["UFP"]["unitframes"]["health"]["texture"]["texture"] = "ElvUI Blank"
	E.db["UFP"]["unitframes"]["power"]["colors"]["transparent_backdrope"] = 0.8
	E.db["UFP"]["unitframes"]["power"]["colors"]["invert_colors"] = true
	E.db["UFP"]["unitframes"]["power"]["colors"]["transparent_statusbar"] = 0.8
	E.db["UFP"]["unitframes"]["power"]["colors"]["backdropcolor"]["b"] = 0.090196078431373
	E.db["UFP"]["unitframes"]["power"]["colors"]["backdropcolor"]["g"] = 0.090196078431373
	E.db["UFP"]["unitframes"]["power"]["colors"]["backdropcolor"]["r"] = 0.090196078431373
	E.db["UFP"]["unitframes"]["power"]["texture"]["texture"] = "ElvUI Blank"
	E.db["UFP"]["unitframes"]["power"]["texture"]["use_Backdrope_texture"] = true
	E.db["UFP"]["unitframes"]["power"]["texture"]["backdrope_texture"] = "fer34"
	E.db["UFP"]["unitframes"]["power"]["texture"]["use_texture"] = true
	E.db["UFP"]["unitframes"]["enable"] = false
	E.db["UFP"]["unitframes"]["use_texture"] = false
	E.db["auras"]["font"] = "Continuum Medium"
	E.db["auras"]["fontOutline"] = "OUTLINE"
	E.db["auras"]["fontSize"] = 12
	E.db["unitframe"]["auraBlacklistModifier"] = "CTRL"
	E.db["unitframe"]["statusbar_backdrop"] = "fer34"
	E.db["unitframe"]["units"]["tank"]["enable"] = false
	E.db["unitframe"]["units"]["party"]["horizontalSpacing"] = 2
	E.db["unitframe"]["units"]["party"]["debuffs"]["anchorPoint"] = "BOTTOMRIGHT"
	E.db["unitframe"]["units"]["party"]["debuffs"]["fontSize"] = 6
	E.db["unitframe"]["units"]["party"]["debuffs"]["sizeOverride"] = 16
	E.db["unitframe"]["units"]["party"]["debuffs"]["useFilter"] = "RaidDebuffs"
	E.db["unitframe"]["units"]["party"]["debuffs"]["xOffset"] = -19
	E.db["unitframe"]["units"]["party"]["debuffs"]["attachTo"] = "HEALTH"
	E.db["unitframe"]["units"]["party"]["debuffs"]["countFontSize"] = 13
	E.db["unitframe"]["units"]["party"]["debuffs"]["yOffset"] = 17
	E.db["unitframe"]["units"]["party"]["portrait"]["overlay"] = true
	E.db["unitframe"]["units"]["party"]["rdebuffs"]["font"] = "Continuum Medium"
	E.db["unitframe"]["units"]["party"]["growthDirection"] = "RIGHT_DOWN"
	E.db["unitframe"]["units"]["party"]["buffIndicator"]["size"] = 13
	E.db["unitframe"]["units"]["party"]["roleIcon"]["xOffset"] = 1
	E.db["unitframe"]["units"]["party"]["roleIcon"]["size"] = 14
	E.db["unitframe"]["units"]["party"]["roleIcon"]["position"] = "TOPLEFT"
	E.db["unitframe"]["units"]["party"]["roleIcon"]["yOffset"] = 4
	E.db["unitframe"]["units"]["party"]["customTexts"] = {}
	E.db["unitframe"]["units"]["party"]["customTexts"]["dead"] = {}
	E.db["unitframe"]["units"]["party"]["customTexts"]["offline"] = {}
	E.db["unitframe"]["units"]["party"]["customTexts"]["dead"]["attachTextTo"] = "HEALTH"
	E.db["unitframe"]["units"]["party"]["customTexts"]["dead"]["font"] = "big_noodle_titling"
	E.db["unitframe"]["units"]["party"]["customTexts"]["dead"]["justifyH"] = "CENTER"
	E.db["unitframe"]["units"]["party"]["customTexts"]["dead"]["fontOutline"] = "OUTLINE"
	E.db["unitframe"]["units"]["party"]["customTexts"]["dead"]["xOffset"] = 0
	E.db["unitframe"]["units"]["party"]["customTexts"]["dead"]["yOffset"] = -11
	E.db["unitframe"]["units"]["party"]["customTexts"]["dead"]["text_format"] = "[dead]"
	E.db["unitframe"]["units"]["party"]["customTexts"]["dead"]["size"] = 12
	E.db["unitframe"]["units"]["party"]["customTexts"]["offline"]["attachTextTo"] = "HEALTH"
	E.db["unitframe"]["units"]["party"]["customTexts"]["offline"]["font"] = "Enigmatic"
	E.db["unitframe"]["units"]["party"]["customTexts"]["offline"]["justifyH"] = "CENTER"
	E.db["unitframe"]["units"]["party"]["customTexts"]["offline"]["fontOutline"] = "OUTLINE"
	E.db["unitframe"]["units"]["party"]["customTexts"]["offline"]["xOffset"] = 0
	E.db["unitframe"]["units"]["party"]["customTexts"]["offline"]["size"] = 8
	E.db["unitframe"]["units"]["party"]["customTexts"]["offline"]["text_format"] = "[offline]"
	E.db["unitframe"]["units"]["party"]["customTexts"]["offline"]["yOffset"] = -11
	E.db["unitframe"]["units"]["party"]["power"]["enable"] = false
	E.db["unitframe"]["units"]["party"]["power"]["position"] = "BOTTOMRIGHT"
	E.db["unitframe"]["units"]["party"]["power"]["text_format"] = ""
	E.db["unitframe"]["units"]["party"]["power"]["yOffset"] = 2
	E.db["unitframe"]["units"]["party"]["orientation"] = "RIGHT"
	E.db["unitframe"]["units"]["party"]["width"] = 100
	E.db["unitframe"]["units"]["party"]["infoPanel"]["height"] = 12
	E.db["unitframe"]["units"]["party"]["health"]["xOffset"] = 0
	E.db["unitframe"]["units"]["party"]["health"]["text_format"] = ""
	E.db["unitframe"]["units"]["party"]["health"]["frequentUpdates"] = true
	E.db["unitframe"]["units"]["party"]["health"]["yOffset"] = 2
	E.db["unitframe"]["units"]["party"]["name"]["text_format"] = "[namecolor][name:short]"
	E.db["unitframe"]["units"]["party"]["buffs"]["anchorPoint"] = "TOPRIGHT"
	E.db["unitframe"]["units"]["party"]["buffs"]["sizeOverride"] = 16
	E.db["unitframe"]["units"]["party"]["buffs"]["useBlacklist"] = false
	E.db["unitframe"]["units"]["party"]["buffs"]["clickThrough"] = true
	E.db["unitframe"]["units"]["party"]["buffs"]["xOffset"] = -1
	E.db["unitframe"]["units"]["party"]["buffs"]["noConsolidated"] = false
	E.db["unitframe"]["units"]["party"]["buffs"]["useFilter"] = "TurtleBuffs"
	E.db["unitframe"]["units"]["party"]["buffs"]["yOffset"] = -17
	E.db["unitframe"]["units"]["party"]["height"] = 50
	E.db["unitframe"]["units"]["party"]["verticalSpacing"] = 2
	E.db["unitframe"]["units"]["raid40"]["horizontalSpacing"] = 1
	E.db["unitframe"]["units"]["raid40"]["debuffs"]["countFontSize"] = 13
	E.db["unitframe"]["units"]["raid40"]["debuffs"]["sizeOverride"] = 20
	E.db["unitframe"]["units"]["raid40"]["debuffs"]["useWhitelist"] = true
	E.db["unitframe"]["units"]["raid40"]["debuffs"]["xOffset"] = -20
	E.db["unitframe"]["units"]["raid40"]["debuffs"]["yOffset"] = 21
	E.db["unitframe"]["units"]["raid40"]["debuffs"]["anchorPoint"] = "BOTTOMRIGHT"
	E.db["unitframe"]["units"]["raid40"]["debuffs"]["clickThrough"] = true
	E.db["unitframe"]["units"]["raid40"]["debuffs"]["fontSize"] = 6
	E.db["unitframe"]["units"]["raid40"]["debuffs"]["enable"] = true
	E.db["unitframe"]["units"]["raid40"]["portrait"]["overlay"] = true
	E.db["unitframe"]["units"]["raid40"]["portrait"]["camDistanceScale"] = 2
	E.db["unitframe"]["units"]["raid40"]["rdebuffs"]["font"] = "Continuum Medium"
	E.db["unitframe"]["units"]["raid40"]["rdebuffs"]["size"] = 26
	E.db["unitframe"]["units"]["raid40"]["growthDirection"] = "DOWN_RIGHT"
	E.db["unitframe"]["units"]["raid40"]["buffIndicator"]["size"] = 13
	E.db["unitframe"]["units"]["raid40"]["roleIcon"]["position"] = "TOPLEFT"
	E.db["unitframe"]["units"]["raid40"]["roleIcon"]["enable"] = true
	E.db["unitframe"]["units"]["raid40"]["roleIcon"]["size"] = 14
	E.db["unitframe"]["units"]["raid40"]["roleIcon"]["xOffset"] = 1
	E.db["unitframe"]["units"]["raid40"]["roleIcon"]["yOffset"] = 4
	E.db["unitframe"]["units"]["raid40"]["customTexts"] = {}
	E.db["unitframe"]["units"]["raid40"]["customTexts"]["dead"] = {}
	E.db["unitframe"]["units"]["raid40"]["customTexts"]["offline"] = {}
	E.db["unitframe"]["units"]["raid40"]["customTexts"]["dead"]["attachTextTo"] = "HEALTH"
	E.db["unitframe"]["units"]["raid40"]["customTexts"]["dead"]["font"] = "Liberation Sans"
	E.db["unitframe"]["units"]["raid40"]["customTexts"]["dead"]["justifyH"] = "CENTER"
	E.db["unitframe"]["units"]["raid40"]["customTexts"]["dead"]["fontOutline"] = "OUTLINE"
	E.db["unitframe"]["units"]["raid40"]["customTexts"]["dead"]["xOffset"] = 0
	E.db["unitframe"]["units"]["raid40"]["customTexts"]["dead"]["size"] = 9
	E.db["unitframe"]["units"]["raid40"]["customTexts"]["dead"]["text_format"] = "[dead]"
	E.db["unitframe"]["units"]["raid40"]["customTexts"]["dead"]["yOffset"] = -11
	E.db["unitframe"]["units"]["raid40"]["customTexts"]["offline"]["attachTextTo"] = "HEALTH"
	E.db["unitframe"]["units"]["raid40"]["customTexts"]["offline"]["font"] = "big_noodle_titling"
	E.db["unitframe"]["units"]["raid40"]["customTexts"]["offline"]["justifyH"] = "CENTER"
	E.db["unitframe"]["units"]["raid40"]["customTexts"]["offline"]["fontOutline"] = "OUTLINE"
	E.db["unitframe"]["units"]["raid40"]["customTexts"]["offline"]["xOffset"] = 0
	E.db["unitframe"]["units"]["raid40"]["customTexts"]["offline"]["size"] = 10
	E.db["unitframe"]["units"]["raid40"]["customTexts"]["offline"]["text_format"] = "[offline]"
	E.db["unitframe"]["units"]["raid40"]["customTexts"]["offline"]["yOffset"] = -11
	E.db["unitframe"]["units"]["raid40"]["width"] = 100
	E.db["unitframe"]["units"]["raid40"]["name"]["yOffset"] = 3
	E.db["unitframe"]["units"]["raid40"]["health"]["text_format"] = ""
	E.db["unitframe"]["units"]["raid40"]["health"]["frequentUpdates"] = true
	E.db["unitframe"]["units"]["raid40"]["health"]["position"] = "LEFT"
	E.db["unitframe"]["units"]["raid40"]["verticalSpacing"] = 1
	E.db["unitframe"]["units"]["raid40"]["height"] = 50
	E.db["unitframe"]["units"]["raid40"]["buffs"]["sizeOverride"] = 16
	E.db["unitframe"]["units"]["raid40"]["buffs"]["useBlacklist"] = false
	E.db["unitframe"]["units"]["raid40"]["buffs"]["noDuration"] = false
	E.db["unitframe"]["units"]["raid40"]["buffs"]["yOffset"] = -17
	E.db["unitframe"]["units"]["raid40"]["buffs"]["onlyHots"] = true
	E.db["unitframe"]["units"]["raid40"]["buffs"]["clickThrough"] = true
	E.db["unitframe"]["units"]["raid40"]["buffs"]["useFilter"] = "TurtleBuffs"
	E.db["unitframe"]["units"]["raid40"]["buffs"]["anchorPoint"] = "TOPRIGHT"
	E.db["unitframe"]["units"]["raid40"]["buffs"]["xOffset"] = -1
	E.db["unitframe"]["units"]["raid40"]["buffs"]["perrow"] = 4
	E.db["unitframe"]["units"]["raid40"]["visibility"] = "[@raid31,noexists] hide;show"
	E.db["unitframe"]["units"]["raidpet"]["horizontalSpacing"] = 1
	E.db["unitframe"]["units"]["raidpet"]["debuffs"]["countFontSize"] = 13
	E.db["unitframe"]["units"]["raidpet"]["debuffs"]["sizeOverride"] = 16
	E.db["unitframe"]["units"]["raidpet"]["debuffs"]["useWhitelist"] = true
	E.db["unitframe"]["units"]["raidpet"]["debuffs"]["xOffset"] = -19
	E.db["unitframe"]["units"]["raidpet"]["debuffs"]["yOffset"] = 17
	E.db["unitframe"]["units"]["raidpet"]["debuffs"]["anchorPoint"] = "BOTTOMRIGHT"
	E.db["unitframe"]["units"]["raidpet"]["debuffs"]["fontSize"] = 6
	E.db["unitframe"]["units"]["raidpet"]["debuffs"]["enable"] = true
	E.db["unitframe"]["units"]["raidpet"]["debuffs"]["perrow"] = 4
	E.db["unitframe"]["units"]["raidpet"]["portrait"]["overlay"] = true
	E.db["unitframe"]["units"]["raidpet"]["portrait"]["camDistanceScale"] = 2
	E.db["unitframe"]["units"]["raidpet"]["groupBy"] = "GROUP"
	E.db["unitframe"]["units"]["raidpet"]["rdebuffs"]["font"] = "Continuum_Medium"
	E.db["unitframe"]["units"]["raidpet"]["rdebuffs"]["enable"] = false
	E.db["unitframe"]["units"]["raidpet"]["rdebuffs"]["yOffset"] = 0
	E.db["unitframe"]["units"]["raidpet"]["numGroups"] = 6
	E.db["unitframe"]["units"]["raidpet"]["width"] = 100
	E.db["unitframe"]["units"]["raidpet"]["verticalSpacing"] = 1
	E.db["unitframe"]["units"]["raidpet"]["name"]["yOffset"] = 0
	E.db["unitframe"]["units"]["raidpet"]["name"]["position"] = "CENTER"
	E.db["unitframe"]["units"]["raidpet"]["health"]["text_format"] = ""
	E.db["unitframe"]["units"]["raidpet"]["health"]["position"] = "LEFT"
	E.db["unitframe"]["units"]["raidpet"]["healPrediction"] = false
	E.db["unitframe"]["units"]["raidpet"]["height"] = 50
	E.db["unitframe"]["units"]["raidpet"]["buffIndicator"]["size"] = 13
	E.db["unitframe"]["units"]["raidpet"]["buffs"]["sizeOverride"] = 16
	E.db["unitframe"]["units"]["raidpet"]["buffs"]["useBlacklist"] = false
	E.db["unitframe"]["units"]["raidpet"]["buffs"]["noDuration"] = false
	E.db["unitframe"]["units"]["raidpet"]["buffs"]["yOffset"] = -17
	E.db["unitframe"]["units"]["raidpet"]["buffs"]["anchorPoint"] = "TOPRIGHT"
	E.db["unitframe"]["units"]["raidpet"]["buffs"]["useFilter"] = "TurtleBuffs"
	E.db["unitframe"]["units"]["raidpet"]["buffs"]["xOffset"] = -1
	E.db["unitframe"]["units"]["raidpet"]["buffs"]["clickThrough"] = true
	E.db["unitframe"]["units"]["raidpet"]["buffs"]["perrow"] = 4
	E.db["unitframe"]["units"]["assist"]["enable"] = false
	E.db["unitframe"]["units"]["raid"]["horizontalSpacing"] = 1
	E.db["unitframe"]["units"]["raid"]["debuffs"]["countFontSize"] = 13
	E.db["unitframe"]["units"]["raid"]["debuffs"]["sizeOverride"] = 20
	E.db["unitframe"]["units"]["raid"]["debuffs"]["useWhitelist"] = true
	E.db["unitframe"]["units"]["raid"]["debuffs"]["xOffset"] = -20
	E.db["unitframe"]["units"]["raid"]["debuffs"]["yOffset"] = 21
	E.db["unitframe"]["units"]["raid"]["debuffs"]["anchorPoint"] = "BOTTOMRIGHT"
	E.db["unitframe"]["units"]["raid"]["debuffs"]["clickThrough"] = true
	E.db["unitframe"]["units"]["raid"]["debuffs"]["fontSize"] = 12
	E.db["unitframe"]["units"]["raid"]["debuffs"]["enable"] = true
	E.db["unitframe"]["units"]["raid"]["portrait"]["overlay"] = true
	E.db["unitframe"]["units"]["raid"]["rdebuffs"]["enable"] = false
	E.db["unitframe"]["units"]["raid"]["rdebuffs"]["font"] = "Continuum Medium"
	E.db["unitframe"]["units"]["raid"]["growthDirection"] = "DOWN_RIGHT"
	E.db["unitframe"]["units"]["raid"]["buffIndicator"]["size"] = 13
	E.db["unitframe"]["units"]["raid"]["roleIcon"]["size"] = 14
	E.db["unitframe"]["units"]["raid"]["roleIcon"]["yOffset"] = 4
	E.db["unitframe"]["units"]["raid"]["power"]["enable"] = false
	E.db["unitframe"]["units"]["raid"]["customTexts"] = {}
	E.db["unitframe"]["units"]["raid"]["customTexts"]["dead"] = {}
	E.db["unitframe"]["units"]["raid"]["customTexts"]["offline"] = {}
	E.db["unitframe"]["units"]["raid"]["customTexts"]["dead"]["attachTextTo"] = "HEALTH"
	E.db["unitframe"]["units"]["raid"]["customTexts"]["dead"]["font"] = "big_noodle_titling"
	E.db["unitframe"]["units"]["raid"]["customTexts"]["dead"]["justifyH"] = "CENTER"
	E.db["unitframe"]["units"]["raid"]["customTexts"]["dead"]["fontOutline"] = "OUTLINE"
	E.db["unitframe"]["units"]["raid"]["customTexts"]["dead"]["xOffset"] = 0
	E.db["unitframe"]["units"]["raid"]["customTexts"]["dead"]["yOffset"] = -11
	E.db["unitframe"]["units"]["raid"]["customTexts"]["dead"]["text_format"] = "[dead]"
	E.db["unitframe"]["units"]["raid"]["customTexts"]["dead"]["size"] = 9
	E.db["unitframe"]["units"]["raid"]["customTexts"]["offline"]["attachTextTo"] = "HEALTH"
	E.db["unitframe"]["units"]["raid"]["customTexts"]["offline"]["font"] = "big_noodle_titling"
	E.db["unitframe"]["units"]["raid"]["customTexts"]["offline"]["justifyH"] = "CENTER"
	E.db["unitframe"]["units"]["raid"]["customTexts"]["offline"]["fontOutline"] = "OUTLINE"
	E.db["unitframe"]["units"]["raid"]["customTexts"]["offline"]["xOffset"] = 0
	E.db["unitframe"]["units"]["raid"]["customTexts"]["offline"]["size"] = 10
	E.db["unitframe"]["units"]["raid"]["customTexts"]["offline"]["text_format"] = "[offline]"
	E.db["unitframe"]["units"]["raid"]["customTexts"]["offline"]["yOffset"] = -11
	E.db["unitframe"]["units"]["raid"]["numGroups"] = 6
	E.db["unitframe"]["units"]["raid"]["width"] = 100
	E.db["unitframe"]["units"]["raid"]["health"]["text_format"] = ""
	E.db["unitframe"]["units"]["raid"]["health"]["frequentUpdates"] = true
	E.db["unitframe"]["units"]["raid"]["health"]["position"] = "LEFT"
	E.db["unitframe"]["units"]["raid"]["name"]["attachTextTo"] = "Frame"
	E.db["unitframe"]["units"]["raid"]["name"]["yOffset"] = 3
	E.db["unitframe"]["units"]["raid"]["buffs"]["sizeOverride"] = 16
	E.db["unitframe"]["units"]["raid"]["buffs"]["useBlacklist"] = false
	E.db["unitframe"]["units"]["raid"]["buffs"]["noDuration"] = false
	E.db["unitframe"]["units"]["raid"]["buffs"]["yOffset"] = -17
	E.db["unitframe"]["units"]["raid"]["buffs"]["onlyHots"] = true
	E.db["unitframe"]["units"]["raid"]["buffs"]["clickThrough"] = true
	E.db["unitframe"]["units"]["raid"]["buffs"]["useFilter"] = "TurtleBuffs"
	E.db["unitframe"]["units"]["raid"]["buffs"]["anchorPoint"] = "TOPRIGHT"
	E.db["unitframe"]["units"]["raid"]["buffs"]["xOffset"] = -1
	E.db["unitframe"]["units"]["raid"]["buffs"]["perrow"] = 4
	E.db["unitframe"]["units"]["raid"]["height"] = 50
	E.db["unitframe"]["units"]["raid"]["verticalSpacing"] = 1
	E.db["unitframe"]["units"]["raid"]["visibility"] = "[@raid6,noexists][@raid31,exists] hide;show"
	E.db["unitframe"]["units"]["focustarget"]["debuffs"]["enable"] = true
	E.db["unitframe"]["units"]["focustarget"]["portrait"]["camDistanceScale"] = 2
	E.db["unitframe"]["units"]["focustarget"]["power"]["enable"] = true
	E.db["unitframe"]["units"]["focustarget"]["power"]["height"] = 5
	E.db["unitframe"]["units"]["focustarget"]["customTexts"] = {}
	E.db["unitframe"]["units"]["focustarget"]["customTexts"]["name1"] = {}
	E.db["unitframe"]["units"]["focustarget"]["customTexts"]["name1"]["attachTextTo"] = "HEALTH"
	E.db["unitframe"]["units"]["focustarget"]["customTexts"]["name1"]["font"] = "big_noodle_titling"
	E.db["unitframe"]["units"]["focustarget"]["customTexts"]["name1"]["justifyH"] = "CENTER"
	E.db["unitframe"]["units"]["focustarget"]["customTexts"]["name1"]["fontOutline"] = "OUTLINE"
	E.db["unitframe"]["units"]["focustarget"]["customTexts"]["name1"]["xOffset"] = 0
	E.db["unitframe"]["units"]["focustarget"]["customTexts"]["name1"]["size"] = 20
	E.db["unitframe"]["units"]["focustarget"]["customTexts"]["name1"]["text_format"] = "[namecolor][name:medium]"
	E.db["unitframe"]["units"]["focustarget"]["customTexts"]["name1"]["yOffset"] = 20
	E.db["unitframe"]["units"]["focustarget"]["width"] = 130
	E.db["unitframe"]["units"]["focustarget"]["infoPanel"]["height"] = 14
	E.db["unitframe"]["units"]["focustarget"]["name"]["text_format"] = ""
	E.db["unitframe"]["units"]["focustarget"]["name"]["yOffset"] = 16
	E.db["unitframe"]["units"]["focustarget"]["enable"] = true
	E.db["unitframe"]["units"]["focustarget"]["height"] = 19
	E.db["unitframe"]["units"]["focustarget"]["health"]["position"] = "LEFT"
	E.db["unitframe"]["units"]["pet"]["debuffs"]["anchorPoint"] = "TOPLEFT"
	E.db["unitframe"]["units"]["pet"]["debuffs"]["enable"] = true
	E.db["unitframe"]["units"]["pet"]["debuffs"]["attachTo"] = "BUFFS"
	E.db["unitframe"]["units"]["pet"]["debuffs"]["perrow"] = 8
	E.db["unitframe"]["units"]["pet"]["debuffs"]["yOffset"] = 7
	E.db["unitframe"]["units"]["pet"]["portrait"]["camDistanceScale"] = 2
	E.db["unitframe"]["units"]["pet"]["castbar"]["iconSize"] = 42
	E.db["unitframe"]["units"]["pet"]["castbar"]["height"] = 17
	E.db["unitframe"]["units"]["pet"]["castbar"]["width"] = 250
	E.db["unitframe"]["units"]["pet"]["castbar"]["insideInfoPanel"] = false
	E.db["unitframe"]["units"]["pet"]["customTexts"] = {}
	E.db["unitframe"]["units"]["pet"]["customTexts"]["name1"] = {}
	E.db["unitframe"]["units"]["pet"]["customTexts"]["name1"]["attachTextTo"] = "HEALTH"
	E.db["unitframe"]["units"]["pet"]["customTexts"]["name1"]["font"] = "big_noodle_titling"
	E.db["unitframe"]["units"]["pet"]["customTexts"]["name1"]["justifyH"] = "CENTER"
	E.db["unitframe"]["units"]["pet"]["customTexts"]["name1"]["fontOutline"] = "OUTLINE"
	E.db["unitframe"]["units"]["pet"]["customTexts"]["name1"]["xOffset"] = 0
	E.db["unitframe"]["units"]["pet"]["customTexts"]["name1"]["yOffset"] = 20
	E.db["unitframe"]["units"]["pet"]["customTexts"]["name1"]["text_format"] = "[difficultycolor][level] [classification] [namecolor][name:medium]"
	E.db["unitframe"]["units"]["pet"]["customTexts"]["name1"]["size"] = 20
	E.db["unitframe"]["units"]["pet"]["width"] = 250
	E.db["unitframe"]["units"]["pet"]["infoPanel"]["height"] = 20
	E.db["unitframe"]["units"]["pet"]["power"]["height"] = 5
	E.db["unitframe"]["units"]["pet"]["power"]["xOffset"] = -2
	E.db["unitframe"]["units"]["pet"]["name"]["text_format"] = ""
	E.db["unitframe"]["units"]["pet"]["buffs"]["enable"] = true
	E.db["unitframe"]["units"]["pet"]["buffs"]["perrow"] = 8
	E.db["unitframe"]["units"]["pet"]["buffs"]["anchorPoint"] = "TOPLEFT"
	E.db["unitframe"]["units"]["pet"]["buffs"]["yOffset"] = 21
	E.db["unitframe"]["units"]["pet"]["orientation"] = "LEFT"
	E.db["unitframe"]["units"]["pet"]["height"] = 19
	E.db["unitframe"]["units"]["pet"]["health"]["xOffset"] = 2
	E.db["unitframe"]["units"]["pet"]["health"]["position"] = "LEFT"
	E.db["unitframe"]["units"]["player"]["debuffs"]["fontSize"] = 22
	E.db["unitframe"]["units"]["player"]["debuffs"]["useBlacklist"] = false
	E.db["unitframe"]["units"]["player"]["debuffs"]["sortDirection"] = "ASCENDING"
	E.db["unitframe"]["units"]["player"]["debuffs"]["sizeOverride"] = 52
	E.db["unitframe"]["units"]["player"]["debuffs"]["perrow"] = 4
	E.db["unitframe"]["units"]["player"]["debuffs"]["yOffset"] = 45
	E.db["unitframe"]["units"]["player"]["portrait"]["overlay"] = true
	E.db["unitframe"]["units"]["player"]["classbar"]["detachFromFrame"] = true
	E.db["unitframe"]["units"]["player"]["classbar"]["detachedWidth"] = 342
	E.db["unitframe"]["units"]["player"]["classbar"]["fill"] = "spaced"
	E.db["unitframe"]["units"]["player"]["classbar"]["height"] = 7
	E.db["unitframe"]["units"]["player"]["classbar"]["additionalPowerText"] = false
	E.db["unitframe"]["units"]["player"]["aurabar"]["maxBars"] = 7
	E.db["unitframe"]["units"]["player"]["aurabar"]["enable"] = false
	E.db["unitframe"]["units"]["player"]["castbar"]["insideInfoPanel"] = false
	E.db["unitframe"]["units"]["player"]["castbar"]["iconAttached"] = false
	E.db["unitframe"]["units"]["player"]["castbar"]["iconYOffset"] = 22
	E.db["unitframe"]["units"]["player"]["castbar"]["width"] = 419
	E.db["unitframe"]["units"]["player"]["castbar"]["iconPosition"] = "CENTER"
	E.db["unitframe"]["units"]["player"]["castbar"]["iconAttachedTo"] = "Castbar"
	E.db["unitframe"]["units"]["player"]["castbar"]["iconXOffset"] = 0
	E.db["unitframe"]["units"]["player"]["castbar"]["height"] = 10
	E.db["unitframe"]["units"]["player"]["castbar"]["iconSize"] = 8
	E.db["unitframe"]["units"]["player"]["castbar"]["icon"] = false
	E.db["unitframe"]["units"]["player"]["castbar"]["latency"] = false
	E.db["unitframe"]["units"]["player"]["power"]["detachFromFrame"] = true
	E.db["unitframe"]["units"]["player"]["power"]["strataAndLevel"]["frameLevel"] = 0
	E.db["unitframe"]["units"]["player"]["power"]["detachedWidth"] = 420
	E.db["unitframe"]["units"]["player"]["power"]["height"] = 14
	E.db["unitframe"]["units"]["player"]["power"]["text_format"] = ""
	E.db["unitframe"]["units"]["player"]["power"]["xOffset"] = 0
	E.db["unitframe"]["units"]["player"]["customTexts"] = {}
	E.db["unitframe"]["units"]["player"]["customTexts"]["hp%"] = {}
	E.db["unitframe"]["units"]["player"]["customTexts"]["mp"] = {}
	E.db["unitframe"]["units"]["player"]["customTexts"]["hp%"]["attachTextTo"] = "Health"
	E.db["unitframe"]["units"]["player"]["customTexts"]["hp%"]["font"] = "big_noodle_titling"
	E.db["unitframe"]["units"]["player"]["customTexts"]["hp%"]["justifyH"] = "CENTER"
	E.db["unitframe"]["units"]["player"]["customTexts"]["hp%"]["fontOutline"] = "OUTLINE"
	E.db["unitframe"]["units"]["player"]["customTexts"]["hp%"]["xOffset"] = 0
	E.db["unitframe"]["units"]["player"]["customTexts"]["hp%"]["yOffset"] = 0
	E.db["unitframe"]["units"]["player"]["customTexts"]["hp%"]["text_format"] = "[healthcolor][health:current] - |cffffffff[perhp]|r"
	E.db["unitframe"]["units"]["player"]["customTexts"]["hp%"]["size"] = 20
	E.db["unitframe"]["units"]["player"]["customTexts"]["mp"]["attachTextTo"] = "Power"
	E.db["unitframe"]["units"]["player"]["customTexts"]["mp"]["font"] = "big_noodle_titling"
	E.db["unitframe"]["units"]["player"]["customTexts"]["mp"]["justifyH"] = "CENTER"
	E.db["unitframe"]["units"]["player"]["customTexts"]["mp"]["fontOutline"] = "OUTLINE"
	E.db["unitframe"]["units"]["player"]["customTexts"]["mp"]["xOffset"] = 0
	E.db["unitframe"]["units"]["player"]["customTexts"]["mp"]["size"] = 20
	E.db["unitframe"]["units"]["player"]["customTexts"]["mp"]["text_format"] = "[powercolor][perpp]"
	E.db["unitframe"]["units"]["player"]["customTexts"]["mp"]["yOffset"] = 0
	E.db["unitframe"]["units"]["player"]["healPrediction"] = false
	E.db["unitframe"]["units"]["player"]["orientation"] = "RIGHT"
	E.db["unitframe"]["units"]["player"]["width"] = 419
	E.db["unitframe"]["units"]["player"]["height"] = 15
	E.db["unitframe"]["units"]["player"]["buffs"]["sizeOverride"] = 52
	E.db["unitframe"]["units"]["player"]["buffs"]["useBlacklist"] = false
	E.db["unitframe"]["units"]["player"]["buffs"]["useWhitelist"] = false
	E.db["unitframe"]["units"]["player"]["buffs"]["noDuration"] = false
	E.db["unitframe"]["units"]["player"]["buffs"]["yOffset"] = 15
	E.db["unitframe"]["units"]["player"]["buffs"]["anchorPoint"] = "TOPRIGHT"
	E.db["unitframe"]["units"]["player"]["buffs"]["fontSize"] = 24
	E.db["unitframe"]["units"]["player"]["buffs"]["sortMethod"] = "DURATION"
	E.db["unitframe"]["units"]["player"]["buffs"]["useFilter"] = "mybuffs"
	E.db["unitframe"]["units"]["player"]["buffs"]["attachTo"] = "FRAME"
	E.db["unitframe"]["units"]["player"]["buffs"]["perrow"] = 4
	E.db["unitframe"]["units"]["player"]["buffs"]["enable"] = true
	E.db["unitframe"]["units"]["player"]["buffs"]["additionalFilterAllowNonPersonal"] = true
	E.db["unitframe"]["units"]["player"]["health"]["text_format"] = ""
	E.db["unitframe"]["units"]["targettarget"]["power"]["height"] = 5
	E.db["unitframe"]["units"]["targettarget"]["customTexts"] = {}
	E.db["unitframe"]["units"]["targettarget"]["customTexts"]["name1"] = {}
	E.db["unitframe"]["units"]["targettarget"]["customTexts"]["name1"]["attachTextTo"] = "HEALTH"
	E.db["unitframe"]["units"]["targettarget"]["customTexts"]["name1"]["font"] = "big_noodle_titling"
	E.db["unitframe"]["units"]["targettarget"]["customTexts"]["name1"]["justifyH"] = "CENTER"
	E.db["unitframe"]["units"]["targettarget"]["customTexts"]["name1"]["fontOutline"] = "OUTLINE"
	E.db["unitframe"]["units"]["targettarget"]["customTexts"]["name1"]["xOffset"] = 0
	E.db["unitframe"]["units"]["targettarget"]["customTexts"]["name1"]["size"] = 20
	E.db["unitframe"]["units"]["targettarget"]["customTexts"]["name1"]["text_format"] = "[namecolor][name:medium]"
	E.db["unitframe"]["units"]["targettarget"]["customTexts"]["name1"]["yOffset"] = 20
	E.db["unitframe"]["units"]["targettarget"]["health"]["position"] = "LEFT"
	E.db["unitframe"]["units"]["targettarget"]["height"] = 19
	E.db["unitframe"]["units"]["targettarget"]["name"]["text_format"] = ""
	E.db["unitframe"]["units"]["targettarget"]["name"]["yOffset"] = 16
	E.db["unitframe"]["units"]["pettarget"]["debuffs"]["enable"] = true
	E.db["unitframe"]["units"]["pettarget"]["portrait"]["camDistanceScale"] = 2
	E.db["unitframe"]["units"]["pettarget"]["power"]["enable"] = true
	E.db["unitframe"]["units"]["pettarget"]["power"]["height"] = 5
	E.db["unitframe"]["units"]["pettarget"]["customTexts"] = {}
	E.db["unitframe"]["units"]["pettarget"]["customTexts"]["name1"] = {}
	E.db["unitframe"]["units"]["pettarget"]["customTexts"]["name1"]["attachTextTo"] = "HEALTH"
	E.db["unitframe"]["units"]["pettarget"]["customTexts"]["name1"]["font"] = "big_noodle_titling"
	E.db["unitframe"]["units"]["pettarget"]["customTexts"]["name1"]["justifyH"] = "CENTER"
	E.db["unitframe"]["units"]["pettarget"]["customTexts"]["name1"]["fontOutline"] = "OUTLINE"
	E.db["unitframe"]["units"]["pettarget"]["customTexts"]["name1"]["xOffset"] = 0
	E.db["unitframe"]["units"]["pettarget"]["customTexts"]["name1"]["yOffset"] = 20
	E.db["unitframe"]["units"]["pettarget"]["customTexts"]["name1"]["text_format"] = "[namecolor][name:medium]"
	E.db["unitframe"]["units"]["pettarget"]["customTexts"]["name1"]["size"] = 20
	E.db["unitframe"]["units"]["pettarget"]["infoPanel"]["height"] = 14
	E.db["unitframe"]["units"]["pettarget"]["name"]["text_format"] = ""
	E.db["unitframe"]["units"]["pettarget"]["name"]["yOffset"] = 16
	E.db["unitframe"]["units"]["pettarget"]["height"] = 19
	E.db["unitframe"]["units"]["pettarget"]["enable"] = true
	E.db["unitframe"]["units"]["pettarget"]["health"]["position"] = "LEFT"
	E.db["unitframe"]["units"]["target"]["debuffs"]["fontSize"] = 26
	E.db["unitframe"]["units"]["target"]["debuffs"]["yOffset"] = 7
	E.db["unitframe"]["units"]["target"]["debuffs"]["anchorPoint"] = "TOPLEFT"
	E.db["unitframe"]["units"]["target"]["debuffs"]["sortMethod"] = "INDEX"
	E.db["unitframe"]["units"]["target"]["debuffs"]["sizeOverride"] = 45
	E.db["unitframe"]["units"]["target"]["debuffs"]["perrow"] = 6
	E.db["unitframe"]["units"]["target"]["power"]["height"] = 5
	E.db["unitframe"]["units"]["target"]["power"]["hideonnpc"] = false
	E.db["unitframe"]["units"]["target"]["power"]["text_format"] = ""
	E.db["unitframe"]["units"]["target"]["power"]["xOffset"] = -2
	E.db["unitframe"]["units"]["target"]["customTexts"] = {}
	E.db["unitframe"]["units"]["target"]["customTexts"]["lvlName"] = {}
	E.db["unitframe"]["units"]["target"]["customTexts"]["hp"] = {}
	E.db["unitframe"]["units"]["target"]["customTexts"]["hp"]["attachTextTo"] = "HEALTH"
	E.db["unitframe"]["units"]["target"]["customTexts"]["hp"]["font"] = "big_noodle_titling"
	E.db["unitframe"]["units"]["target"]["customTexts"]["hp"]["justifyH"] = "RIGHT"
	E.db["unitframe"]["units"]["target"]["customTexts"]["hp"]["fontOutline"] = "OUTLINE"
	E.db["unitframe"]["units"]["target"]["customTexts"]["hp"]["xOffset"] = 0
	E.db["unitframe"]["units"]["target"]["customTexts"]["hp"]["yOffset"] = 21
	E.db["unitframe"]["units"]["target"]["customTexts"]["hp"]["text_format"] = "[healthcolor][health:current] - |cffffffff[perhp]|r"
	E.db["unitframe"]["units"]["target"]["customTexts"]["hp"]["size"] = 20
	E.db["unitframe"]["units"]["target"]["customTexts"]["lvlName"]["attachTextTo"] = "HEALTH"
	E.db["unitframe"]["units"]["target"]["customTexts"]["lvlName"]["font"] = "big_noodle_titling"
	E.db["unitframe"]["units"]["target"]["customTexts"]["lvlName"]["justifyH"] = "LEFT"
	E.db["unitframe"]["units"]["target"]["customTexts"]["lvlName"]["fontOutline"] = "OUTLINE"
	E.db["unitframe"]["units"]["target"]["customTexts"]["lvlName"]["xOffset"] = 0
	E.db["unitframe"]["units"]["target"]["customTexts"]["lvlName"]["yOffset"] = 20
	E.db["unitframe"]["units"]["target"]["customTexts"]["lvlName"]["text_format"] = "[difficultycolor][level] [classification] [namecolor][name:medium]"
	E.db["unitframe"]["units"]["target"]["customTexts"]["lvlName"]["size"] = 20
	E.db["unitframe"]["units"]["target"]["name"]["text_format"] = ""
	E.db["unitframe"]["units"]["target"]["width"] = 250
	E.db["unitframe"]["units"]["target"]["orientation"] = "LEFT"
	E.db["unitframe"]["units"]["target"]["health"]["xOffset"] = 2
	E.db["unitframe"]["units"]["target"]["health"]["text_format"] = ""
	E.db["unitframe"]["units"]["target"]["health"]["position"] = "LEFT"
	E.db["unitframe"]["units"]["target"]["castbar"]["height"] = 17
	E.db["unitframe"]["units"]["target"]["castbar"]["width"] = 250
	E.db["unitframe"]["units"]["target"]["castbar"]["insideInfoPanel"] = false
	E.db["unitframe"]["units"]["target"]["height"] = 19
	E.db["unitframe"]["units"]["target"]["buffs"]["fontSize"] = 17
	E.db["unitframe"]["units"]["target"]["buffs"]["yOffset"] = 21
	E.db["unitframe"]["units"]["target"]["buffs"]["anchorPoint"] = "TOPLEFT"
	E.db["unitframe"]["units"]["target"]["smartAuraDisplay"] = "DISABLED"
	E.db["unitframe"]["units"]["target"]["aurabar"]["maxDuration"] = 120
	E.db["unitframe"]["units"]["target"]["aurabar"]["maxBars"] = 7
	E.db["unitframe"]["units"]["target"]["aurabar"]["enable"] = false
	E.db["unitframe"]["units"]["arena"]["enable"] = false
	E.db["unitframe"]["units"]["focus"]["debuffs"]["fontSize"] = 26
	E.db["unitframe"]["units"]["focus"]["debuffs"]["yOffset"] = 7
	E.db["unitframe"]["units"]["focus"]["debuffs"]["anchorPoint"] = "TOPLEFT"
	E.db["unitframe"]["units"]["focus"]["debuffs"]["sizeOverride"] = 45
	E.db["unitframe"]["units"]["focus"]["debuffs"]["attachTo"] = "BUFFS"
	E.db["unitframe"]["units"]["focus"]["debuffs"]["perrow"] = 4
	E.db["unitframe"]["units"]["focus"]["castbar"]["iconSize"] = 42
	E.db["unitframe"]["units"]["focus"]["castbar"]["height"] = 17
	E.db["unitframe"]["units"]["focus"]["castbar"]["width"] = 250
	E.db["unitframe"]["units"]["focus"]["castbar"]["insideInfoPanel"] = false
	E.db["unitframe"]["units"]["focus"]["customTexts"] = {}
	E.db["unitframe"]["units"]["focus"]["customTexts"]["lvlName"] = {}
	E.db["unitframe"]["units"]["focus"]["customTexts"]["hp"] = {}
	E.db["unitframe"]["units"]["focus"]["customTexts"]["hp"]["attachTextTo"] = "HEALTH"
	E.db["unitframe"]["units"]["focus"]["customTexts"]["hp"]["font"] = "big_noodle_titling"
	E.db["unitframe"]["units"]["focus"]["customTexts"]["hp"]["justifyH"] = "RIGHT"
	E.db["unitframe"]["units"]["focus"]["customTexts"]["hp"]["fontOutline"] = "OUTLINE"
	E.db["unitframe"]["units"]["focus"]["customTexts"]["hp"]["xOffset"] = 0
	E.db["unitframe"]["units"]["focus"]["customTexts"]["hp"]["yOffset"] = 21
	E.db["unitframe"]["units"]["focus"]["customTexts"]["hp"]["text_format"] = "[healthcolor][health:current] - |cffffffff[perhp]|r"
	E.db["unitframe"]["units"]["focus"]["customTexts"]["hp"]["size"] = 20
	E.db["unitframe"]["units"]["focus"]["customTexts"]["lvlName"]["attachTextTo"] = "HEALTH"
	E.db["unitframe"]["units"]["focus"]["customTexts"]["lvlName"]["font"] = "big_noodle_titling"
	E.db["unitframe"]["units"]["focus"]["customTexts"]["lvlName"]["justifyH"] = "LEFT"
	E.db["unitframe"]["units"]["focus"]["customTexts"]["lvlName"]["fontOutline"] = "OUTLINE"
	E.db["unitframe"]["units"]["focus"]["customTexts"]["lvlName"]["xOffset"] = 0
	E.db["unitframe"]["units"]["focus"]["customTexts"]["lvlName"]["yOffset"] = 20
	E.db["unitframe"]["units"]["focus"]["customTexts"]["lvlName"]["text_format"] = "[difficultycolor][level] [classification] [namecolor][name:medium]"
	E.db["unitframe"]["units"]["focus"]["customTexts"]["lvlName"]["size"] = 20
	E.db["unitframe"]["units"]["focus"]["width"] = 250
	E.db["unitframe"]["units"]["focus"]["infoPanel"]["height"] = 20
	E.db["unitframe"]["units"]["focus"]["power"]["xOffset"] = -2
	E.db["unitframe"]["units"]["focus"]["power"]["height"] = 5
	E.db["unitframe"]["units"]["focus"]["name"]["text_format"] = ""
	E.db["unitframe"]["units"]["focus"]["height"] = 19
	E.db["unitframe"]["units"]["focus"]["orientation"] = "LEFT"
	E.db["unitframe"]["units"]["focus"]["buffs"]["selfBuffs"] = true
	E.db["unitframe"]["units"]["focus"]["buffs"]["enable"] = true
	E.db["unitframe"]["units"]["focus"]["buffs"]["playerOnly"]["friendly"] = false
	E.db["unitframe"]["units"]["focus"]["buffs"]["yOffset"] = 21
	E.db["unitframe"]["units"]["focus"]["buffs"]["anchorPoint"] = "TOPLEFT"
	E.db["unitframe"]["units"]["focus"]["buffs"]["perrow"] = 8
	E.db["unitframe"]["units"]["focus"]["buffs"]["noDuration"]["friendly"] = false
	E.db["unitframe"]["units"]["focus"]["buffs"]["fontSize"] = 18
	E.db["unitframe"]["units"]["focus"]["health"]["xOffset"] = 2
	E.db["unitframe"]["units"]["focus"]["health"]["position"] = "LEFT"
	E.db["unitframe"]["units"]["focus"]["aurabar"]["selfBuffs"] = true
	E.db["unitframe"]["units"]["focus"]["aurabar"]["maxBars"] = 7
	E.db["unitframe"]["units"]["boss"]["debuffs"]["numrows"] = 1
	E.db["unitframe"]["units"]["boss"]["debuffs"]["fontSize"] = 19
	E.db["unitframe"]["units"]["boss"]["debuffs"]["yOffset"] = 10
	E.db["unitframe"]["units"]["boss"]["debuffs"]["sizeOverride"] = 39
	E.db["unitframe"]["units"]["boss"]["debuffs"]["xOffset"] = -4
	E.db["unitframe"]["units"]["boss"]["castbar"]["iconAttached"] = false
	E.db["unitframe"]["units"]["boss"]["castbar"]["height"] = 13
	E.db["unitframe"]["units"]["boss"]["castbar"]["iconSize"] = 16
	E.db["unitframe"]["units"]["boss"]["castbar"]["icon"] = false
	E.db["unitframe"]["units"]["boss"]["castbar"]["width"] = 250
	E.db["unitframe"]["units"]["boss"]["customTexts"] = {}
	E.db["unitframe"]["units"]["boss"]["customTexts"]["lvlName"] = {}
	E.db["unitframe"]["units"]["boss"]["customTexts"]["hp"] = {}
	E.db["unitframe"]["units"]["boss"]["customTexts"]["lvlName"]["attachTextTo"] = "Frame"
	E.db["unitframe"]["units"]["boss"]["customTexts"]["lvlName"]["font"] = "big_noodle_titling"
	E.db["unitframe"]["units"]["boss"]["customTexts"]["lvlName"]["justifyH"] = "LEFT"
	E.db["unitframe"]["units"]["boss"]["customTexts"]["lvlName"]["fontOutline"] = "OUTLINE"
	E.db["unitframe"]["units"]["boss"]["customTexts"]["lvlName"]["xOffset"] = 0
	E.db["unitframe"]["units"]["boss"]["customTexts"]["lvlName"]["size"] = 20
	E.db["unitframe"]["units"]["boss"]["customTexts"]["lvlName"]["text_format"] = "[level] [classification] | [namecolor][name:medium]"
	E.db["unitframe"]["units"]["boss"]["customTexts"]["lvlName"]["yOffset"] = 20
	E.db["unitframe"]["units"]["boss"]["customTexts"]["hp"]["attachTextTo"] = "Frame"
	E.db["unitframe"]["units"]["boss"]["customTexts"]["hp"]["font"] = "big_noodle_titling"
	E.db["unitframe"]["units"]["boss"]["customTexts"]["hp"]["justifyH"] = "RIGHT"
	E.db["unitframe"]["units"]["boss"]["customTexts"]["hp"]["fontOutline"] = "OUTLINE"
	E.db["unitframe"]["units"]["boss"]["customTexts"]["hp"]["xOffset"] = 0
	E.db["unitframe"]["units"]["boss"]["customTexts"]["hp"]["size"] = 20
	E.db["unitframe"]["units"]["boss"]["customTexts"]["hp"]["text_format"] = "[healthcolor][health:current] - |cffffffff[perhp]|r"
	E.db["unitframe"]["units"]["boss"]["customTexts"]["hp"]["yOffset"] = 20
	E.db["unitframe"]["units"]["boss"]["width"] = 250
	E.db["unitframe"]["units"]["boss"]["growthDirection"] = "UP"
	E.db["unitframe"]["units"]["boss"]["health"]["xOffset"] = -1
	E.db["unitframe"]["units"]["boss"]["health"]["yOffset"] = 18
	E.db["unitframe"]["units"]["boss"]["health"]["text_format"] = ""
	E.db["unitframe"]["units"]["boss"]["health"]["position"] = "RIGHT"
	E.db["unitframe"]["units"]["boss"]["name"]["xOffset"] = 9
	E.db["unitframe"]["units"]["boss"]["name"]["yOffset"] = 12
	E.db["unitframe"]["units"]["boss"]["name"]["text_format"] = ""
	E.db["unitframe"]["units"]["boss"]["name"]["position"] = "TOPLEFT"
	E.db["unitframe"]["units"]["boss"]["spacing"] = 37
	E.db["unitframe"]["units"]["boss"]["height"] = 19
	E.db["unitframe"]["units"]["boss"]["buffs"]["fontSize"] = 19
	E.db["unitframe"]["units"]["boss"]["buffs"]["yOffset"] = 7
	E.db["unitframe"]["units"]["boss"]["buffs"]["anchorPoint"] = "RIGHT"
	E.db["unitframe"]["units"]["boss"]["buffs"]["sizeOverride"] = 30
	E.db["unitframe"]["units"]["boss"]["buffs"]["xOffset"] = 7
	E.db["unitframe"]["units"]["boss"]["power"]["text_format"] = ""
	E.db["unitframe"]["units"]["boss"]["power"]["height"] = 5
	E.db["unitframe"]["OORAlpha"] = 0.33
	E.db["unitframe"]["font"] = "big_noodle_titling"
	E.db["unitframe"]["colors"]["backdropTex_healh"] = true
	E.db["unitframe"]["colors"]["colorhealthbyvalue"] = false
	E.db["unitframe"]["colors"]["customhealthbackdrop"] = true
	E.db["unitframe"]["colors"]["texture_power"] = true
	E.db["unitframe"]["colors"]["borderColor"]["r"] = 0.090196078431373
	E.db["unitframe"]["colors"]["borderColor"]["g"] = 0.090196078431373
	E.db["unitframe"]["colors"]["borderColor"]["b"] = 0.090196078431373
	E.db["unitframe"]["colors"]["auraBarBuff"]["r"] = 0.1
	E.db["unitframe"]["colors"]["auraBarBuff"]["g"] = 0.1
	E.db["unitframe"]["colors"]["auraBarBuff"]["b"] = 0.1
	E.db["unitframe"]["colors"]["classResources"]["bgColor"]["r"] = 0.11764705882353
	E.db["unitframe"]["colors"]["classResources"]["bgColor"]["g"] = 0.11764705882353
	E.db["unitframe"]["colors"]["classResources"]["bgColor"]["b"] = 0.11764705882353
	E.db["unitframe"]["colors"]["health"]["a"] = 0.8500000089407
	E.db["unitframe"]["colors"]["health"]["r"] = 0.090196078431373
	E.db["unitframe"]["colors"]["health"]["g"] = 0.090196078431373
	E.db["unitframe"]["colors"]["health"]["b"] = 0.090196078431373
	E.db["unitframe"]["colors"]["health_backdrop_dead"]["a"] = 0.8500000089407
	E.db["unitframe"]["colors"]["health_backdrop_dead"]["g"] = 0.011764705882353
	E.db["unitframe"]["colors"]["health_backdrop_dead"]["b"] = 0.011764705882353
	E.db["unitframe"]["colors"]["power"]["MANA"]["r"] = 0.42745098039216
	E.db["unitframe"]["colors"]["power"]["MANA"]["g"] = 0.61960784313726
	E.db["unitframe"]["colors"]["power"]["MANA"]["b"] = 0.87843137254902
	E.db["unitframe"]["colors"]["castColor"]["a"] = 1
	E.db["unitframe"]["colors"]["castColor"]["r"] = 1
	E.db["unitframe"]["colors"]["castColor"]["g"] = 0.89019607843137
	E.db["unitframe"]["colors"]["castColor"]["b"] = 0.67058823529412
	E.db["unitframe"]["colors"]["healPrediction"]["absorbs"]["a"] = 0.8200000077486
	E.db["unitframe"]["colors"]["healPrediction"]["absorbs"]["r"] = 0.45882352941177
	E.db["unitframe"]["colors"]["healPrediction"]["absorbs"]["b"] = 0.99607843137255
	E.db["unitframe"]["colors"]["customhealthraidframe"] = false
	E.db["unitframe"]["colors"]["disconnected"]["a"] = 0.8500000089407
	E.db["unitframe"]["colors"]["disconnected"]["r"] = 0.83921568627451
	E.db["unitframe"]["colors"]["disconnected"]["g"] = 0.74901960784314
	E.db["unitframe"]["colors"]["disconnected"]["b"] = 0.65098039215686
	E.db["unitframe"]["colors"]["castNoInterrupt"]["a"] = 1
	E.db["unitframe"]["colors"]["castNoInterrupt"]["r"] = 0.78039215686274
	E.db["unitframe"]["colors"]["castNoInterrupt"]["g"] = 0.45882352941177
	E.db["unitframe"]["colors"]["castNoInterrupt"]["b"] = 0.23137254901961
	E.db["unitframe"]["colors"]["tapped"]["a"] = 0.8500000089407
	E.db["unitframe"]["colors"]["tapped"]["r"] = 0.54901960784314
	E.db["unitframe"]["colors"]["tapped"]["g"] = 0.56862745098039
	E.db["unitframe"]["colors"]["tapped"]["b"] = 0.61176470588235
	E.db["unitframe"]["colors"]["backdropTex_power"] = true
	E.db["unitframe"]["colors"]["texture_healh"] = true
	E.db["unitframe"]["colors"]["auraBarDebuff"]["r"] = 0.07843137254902
	E.db["unitframe"]["colors"]["auraBarDebuff"]["g"] = 0.07843137254902
	E.db["unitframe"]["colors"]["auraBarDebuff"]["b"] = 0.07843137254902
	E.db["unitframe"]["colors"]["health_backdrop"]["a"] = 0.8500000089407
	E.db["unitframe"]["colors"]["health_backdrop"]["r"] = 0.82745098039216
	E.db["unitframe"]["colors"]["health_backdrop"]["g"] = 0.82745098039216
	E.db["unitframe"]["colors"]["health_backdrop"]["b"] = 0.82745098039216
	E.db["unitframe"]["fontOutline"] = "OUTLINE"
	E.db["unitframe"]["statusbar"] = "fer34"
	E.db["unitframe"]["fontSize"] = 14
	E.db["CustomTweaks"]["PushedColor"]["Color"]["a"] = 0.47000002861023
	E.db["CustomTweaks"]["PushedColor"]["Color"]["r"] = 0.81960784313725
	E.db["CustomTweaks"]["PushedColor"]["Color"]["g"] = 0.31372549019608
	E.db["CustomTweaks"]["PushedColor"]["Color"]["b"] = 0.28235294117647
	E.db["CustomTweaks"]["CastbarText"]["Player"]["duration"]["color"]["b"] = 0.65098039215686
	E.db["CustomTweaks"]["CastbarText"]["Player"]["duration"]["color"]["g"] = 0.74901960784314
	E.db["CustomTweaks"]["CastbarText"]["Player"]["duration"]["color"]["r"] = 0.83921568627451
	E.db["CustomTweaks"]["CastbarText"]["Player"]["text"]["color"]["r"] = 0.83921568627451
	E.db["CustomTweaks"]["CastbarText"]["Player"]["text"]["color"]["g"] = 0.74901960784314
	E.db["CustomTweaks"]["CastbarText"]["Player"]["text"]["color"]["b"] = 0.65098039215686
	E.db["CustomTweaks"]["CastbarText"]["Player"]["text"]["point"] = "CENTER"
	E.db["CustomTweaks"]["CastbarText"]["Player"]["text"]["yOffset"] = 5
	E.db["CustomTweaks"]["CastbarCustomBackdrop"]["backdropColor"]["a"] = 0.8500000089407
	E.db["CustomTweaks"]["CastbarCustomBackdrop"]["backdropColor"]["b"] = 0.090196078431373
	E.db["CustomTweaks"]["CastbarCustomBackdrop"]["backdropColor"]["g"] = 0.090196078431373
	E.db["CustomTweaks"]["CastbarCustomBackdrop"]["backdropColor"]["r"] = 0.090196078431373
	E.db["datatexts"]["minimapTopRight"] = true
	E.db["datatexts"]["enable"] = true
	E.db["datatexts"]["time24"] = true
	E.db["datatexts"]["fontOutline"] = "OUTLINE"
	E.db["datatexts"]["leftChatPanel"] = false
	E.db["datatexts"]["goldCoins"] = true
	E.db["datatexts"]["rightChatPanel"] = false
	E.db["datatexts"]["minimapBottomLeft"] = true
	E.db["datatexts"]["minimapBottom"] = true
	E.db["datatexts"]["minimapTopLeft"] = true
	E.db["datatexts"]["goldFormat"] = "SMART"
	E.db["datatexts"]["minimapPanels"] = false
	E.db["datatexts"]["dataText1Panels"] = true
	E.db["datatexts"]["font"] = "big_noodle_titling"
	E.db["datatexts"]["minimapBottomRight"] = true
	E.db["datatexts"]["minimapTop"] = true
	E.db["datatexts"]["pos1"] = "Time"
	E.db["datatexts"]["panels"]["LeftMiniPanel"] = ""
	E.db["datatexts"]["panels"]["TopLeftMiniPanel"] = "Orderhall"
	E.db["datatexts"]["panels"]["RightChatDataPanel"]["right"] = ""
	E.db["datatexts"]["panels"]["RightChatDataPanel"]["left"] = ""
	E.db["datatexts"]["panels"]["RightChatDataPanel"]["middle"] = ""
	E.db["datatexts"]["panels"]["enable"] = false
	E.db["datatexts"]["panels"]["LeftChatDataPanel"]["right"] = ""
	E.db["datatexts"]["panels"]["LeftChatDataPanel"]["left"] = ""
	E.db["datatexts"]["panels"]["LeftChatDataPanel"]["middle"] = ""
	E.db["datatexts"]["panels"]["BottomMiniPanel"] = "ExRT"
	E.db["datatexts"]["panels"]["RightMiniPanel"] = ""
	E.db["datatexts"]["panels"]["BottomRightMiniPanel"] = "BigWigs"
	E.db["datatexts"]["panels"]["BottomLeftMiniPanel"] = "SavedInstances"
	E.db["datatexts"]["panels"]["TopRightMiniPanel"] = "BugSack"
	E.db["actionbar"]["bar3"]["buttonsize"] = 34
	E.db["actionbar"]["bar3"]["alpha"] = 0.7
	E.db["actionbar"]["bar3"]["buttons"] = 12
	E.db["actionbar"]["bar3"]["buttonsPerRow"] = 12
	E.db["actionbar"]["bar3"]["backdropSpacing"] = 1
	E.db["actionbar"]["bar3"]["buttonspacing"] = 1
	E.db["actionbar"]["bar6"]["enabled"] = true
	E.db["actionbar"]["bar6"]["showGrid"] = false
	E.db["actionbar"]["bar6"]["buttons"] = 2
	E.db["actionbar"]["bar6"]["buttonspacing"] = 1
	E.db["actionbar"]["bar6"]["buttonsPerRow"] = 1
	E.db["actionbar"]["bar6"]["alpha"] = 0.7
	E.db["actionbar"]["extraActionButton"]["scale"] = 0.8
	E.db["actionbar"]["microbar"]["scale"] = 0.96
	E.db["actionbar"]["microbar"]["symbolic"] = true
	E.db["actionbar"]["microbar"]["alpha"] = 0.8
	E.db["actionbar"]["bar2"]["enabled"] = true
	E.db["actionbar"]["bar2"]["buttonsize"] = 29
	E.db["actionbar"]["bar2"]["alpha"] = 0.8
	E.db["actionbar"]["bar2"]["buttons"] = 6
	E.db["actionbar"]["bar2"]["buttonspacing"] = 1
	E.db["actionbar"]["bar2"]["buttonsPerRow"] = 6
	E.db["actionbar"]["bar2"]["backdropSpacing"] = 1
	E.db["actionbar"]["bar1"]["buttonsize"] = 34
	E.db["actionbar"]["bar1"]["alpha"] = 0.7
	E.db["actionbar"]["bar1"]["buttonspacing"] = 1
	E.db["actionbar"]["bar5"]["showGrid"] = false
	E.db["actionbar"]["bar5"]["buttons"] = 2
	E.db["actionbar"]["bar5"]["buttonsPerRow"] = 1
	E.db["actionbar"]["bar5"]["alpha"] = 0.7
	E.db["actionbar"]["bar5"]["buttonspacing"] = 1
	E.db["actionbar"]["backdropSpacingConverted"] = true
	E.db["actionbar"]["font"] = "Continuum Medium"
	E.db["actionbar"]["macrotext"] = true
	E.db["actionbar"]["stanceBar"]["buttonspacing"] = 1
	E.db["actionbar"]["stanceBar"]["style"] = "classic"
	E.db["actionbar"]["stanceBar"]["alpha"] = 0.86
	E.db["actionbar"]["barPet"]["buttonspacing"] = 1
	E.db["actionbar"]["barPet"]["alpha"] = 0.7
	E.db["actionbar"]["barPet"]["backdrop"] = false
	E.db["actionbar"]["bar4"]["buttonsize"] = 29
	E.db["actionbar"]["bar4"]["backdrop"] = false
	E.db["actionbar"]["bar4"]["buttons"] = 7
	E.db["actionbar"]["bar4"]["buttonspacing"] = 1
	E.db["actionbar"]["bar4"]["backdropSpacing"] = 1
	E.db["actionbar"]["bar4"]["alpha"] = 0.8
	E.db["nameplates"]["statusbar"] = "fer34"
	E.db["nameplates"]["units"]["PLAYER"]["debuffs"]["baseHeight"] = 40
	E.db["nameplates"]["units"]["PLAYER"]["castbar"]["enable"] = false
	E.db["nameplates"]["units"]["PLAYER"]["powerbar"]["enable"] = false
	E.db["nameplates"]["units"]["PLAYER"]["buffs"]["baseHeight"] = 40
	E.db["nameplates"]["units"]["PLAYER"]["visibility"]["showWithTarget"] = true
	E.db["nameplates"]["units"]["PLAYER"]["visibility"]["showAlways"] = true
	E.db["nameplates"]["units"]["PLAYER"]["enable"] = false
	E.db["nameplates"]["units"]["FRIENDLY_NPC"]["debuffs"]["numAuras"] = 5
	E.db["nameplates"]["units"]["FRIENDLY_NPC"]["debuffs"]["baseHeight"] = 30
	E.db["nameplates"]["units"]["FRIENDLY_NPC"]["debuffs"]["filters"]["maxDuration"] = 147
	E.db["nameplates"]["units"]["FRIENDLY_NPC"]["healthbar"]["enable"] = true
	E.db["nameplates"]["units"]["FRIENDLY_NPC"]["healthbar"]["text"]["enable"] = true
	E.db["nameplates"]["units"]["FRIENDLY_NPC"]["healthbar"]["height"] = 15
	E.db["nameplates"]["units"]["FRIENDLY_NPC"]["healthbar"]["width"] = 170
	E.db["nameplates"]["units"]["FRIENDLY_NPC"]["castbar"]["enable"] = true
	E.db["nameplates"]["units"]["FRIENDLY_NPC"]["castbar"]["height"] = 12
	E.db["nameplates"]["units"]["FRIENDLY_NPC"]["buffs"]["numAuras"] = 5
	E.db["nameplates"]["units"]["FRIENDLY_NPC"]["buffs"]["baseHeight"] = 30
	E.db["nameplates"]["units"]["FRIENDLY_PLAYER"]["debuffs"]["numAuras"] = 5
	E.db["nameplates"]["units"]["FRIENDLY_PLAYER"]["debuffs"]["baseHeight"] = 30
	E.db["nameplates"]["units"]["FRIENDLY_PLAYER"]["healthbar"]["enable"] = true
	E.db["nameplates"]["units"]["FRIENDLY_PLAYER"]["buffs"]["baseHeight"] = 30
	E.db["nameplates"]["units"]["FRIENDLY_PLAYER"]["buffs"]["numAuras"] = 5
	E.db["nameplates"]["units"]["HEALER"]["buffs"]["numAuras"] = 5
	E.db["nameplates"]["units"]["HEALER"]["buffs"]["baseHeight"] = 30
	E.db["nameplates"]["units"]["ENEMY_PLAYER"]["debuffs"]["numAuras"] = 5
	E.db["nameplates"]["units"]["ENEMY_PLAYER"]["debuffs"]["baseHeight"] = 30
	E.db["nameplates"]["units"]["ENEMY_PLAYER"]["buffs"]["numAuras"] = 5
	E.db["nameplates"]["units"]["ENEMY_PLAYER"]["buffs"]["baseHeight"] = 30
	E.db["nameplates"]["units"]["ENEMY_NPC"]["debuffs"]["numAuras"] = 5
	E.db["nameplates"]["units"]["ENEMY_NPC"]["debuffs"]["baseHeight"] = 30
	E.db["nameplates"]["units"]["ENEMY_NPC"]["debuffs"]["filters"]["maxDuration"] = 147
	E.db["nameplates"]["units"]["ENEMY_NPC"]["healthbar"]["height"] = 15
	E.db["nameplates"]["units"]["ENEMY_NPC"]["healthbar"]["text"]["enable"] = true
	E.db["nameplates"]["units"]["ENEMY_NPC"]["healthbar"]["width"] = 170
	E.db["nameplates"]["units"]["ENEMY_NPC"]["castbar"]["height"] = 12
	E.db["nameplates"]["units"]["ENEMY_NPC"]["buffs"]["numAuras"] = 5
	E.db["nameplates"]["units"]["ENEMY_NPC"]["buffs"]["baseHeight"] = 30
	E.db["nameplates"]["lowHealthThreshold"] = 0
	E.db["nameplates"]["font"] = "big_noodle_titling"
	E.db["nameplates"]["showNPCTitles"] = false
	E.db["nameplates"]["fontOutline"] = "OUTLINE"
	E.db["nameplates"]["classbar"]["attachTo"] = "PLAYER"
	E.db["nameplates"]["fontSize"] = 14
	E.db["bossAuraFiltersConverted"] = true
	E.db["cooldown"]["threshold"] = 1
	E.db["chat"]["chatHistory"] = false
	E.db["chat"]["fontSize"] = 12
	E.db["chat"]["tabFontOutline"] = "OUTLINE"
	E.db["chat"]["tabFont"] = "Continuum Medium"
	E.db["chat"]["font"] = "Continuum Medium"
	E.db["chat"]["lockPositions"] = false
	E.db["chat"]["tapFontSize"] = 12
	E.db["chat"]["panelBackdrop"] = "HIDEBOTH"

	E.private["CustomTweaks"]["CastbarCustomBackdrop"] = true
	E.private["CustomTweaks"]["CastbarText"] = true
	E.private["general"]["normTex"] = "fer34"
	E.private["general"]["glossTex"] = "ElvUI Blank"
	E.private["general"]["dmgfont"] = "big_noodle_titling"
	E.private["general"]["namefont"] = "big_noodle_titling"
	E.private["install_complete"] = "E.version"

	--Возвращаем критические настройки
	E.db.layoutSet = layout
	--E.private["install_complete"] = install

	E:UpdateAll(true)
	E:StaticPopup_Show("PRIVATE_RL")
end

local function noname()

	--player
	E.db["unitframe"]["units"]["player"]["name"]["text_format"] = ""
	--E.db["unitframe"]["units"]["raid40"]["name"]["text_format"] = "[namecolor][class]"
	
	--target
	E.db["unitframe"]["units"]["target"]["name"]["text_format"] = ""
	--E.db["unitframe"]["units"]["target"]["name"]["text_format"] = "[namecolor][class]"
	E.db["unitframe"]["units"]["target"]["customTexts"]["lvlName"]["text_format"] = "[difficultycolor][level] [classification] [namecolor][class]"
	
	--targettarget
	E.db["unitframe"]["units"]["targettarget"]["name"]["text_format"] = ""
	--E.db["unitframe"]["units"]["targettarget"]["name"]["text_format"] = "[namecolor][class]"
	E.db["unitframe"]["units"]["targettarget"]["customTexts"]["name1"]["text_format"] = "[namecolor][class]"
	
	--focus
	E.db["unitframe"]["units"]["focus"]["name"]["text_format"] = ""
	--E.db["unitframe"]["units"]["focus"]["name"]["text_format"] = "[namecolor][class]"
	E.db["unitframe"]["units"]["focus"]["customTexts"]["lvlName"]["text_format"] = "[difficultycolor][level] [classification] [namecolor][class]"
	
	--focustarget
	E.db["unitframe"]["units"]["focustarget"]["name"]["text_format"] = ""
	--E.db["unitframe"]["units"]["focustarget"]["name"]["text_format"] = "[namecolor][class]"
	E.db["unitframe"]["units"]["focustarget"]["customTexts"]["name1"]["text_format"] = "[namecolor][class]"
	
	--party
	--E.db["unitframe"]["units"]["party"]["name"]["text_format"] = ""
	E.db["unitframe"]["units"]["party"]["name"]["text_format"] = "[namecolor][class]"
	
	--raid
	--E.db["unitframe"]["units"]["raid"]["name"]["text_format"] = ""
	E.db["unitframe"]["units"]["raid"]["name"]["text_format"] = "[namecolor][class]"
	
	--raid40
	--E.db["unitframe"]["units"]["raid40"]["name"]["text_format"] = ""
	E.db["unitframe"]["units"]["raid40"]["name"]["text_format"] = "[namecolor][class]"
	
	--pettarget
	E.db["unitframe"]["units"]["pettarget"]["name"]["text_format"] = ""
	E.db["unitframe"]["units"]["pettarget"]["customTexts"]["name1"]["text_format"] = "[namecolor][class]"

	E:UpdateAll(true)
	E:StaticPopup_Show("PRIVATE_RL")
end

local function return_name()
	--player
	E.db["unitframe"]["units"]["player"]["name"]["text_format"] = ""
	--E.db["unitframe"]["units"]["raid40"]["name"]["text_format"] = "[namecolor][class]"
	
	--target
	E.db["unitframe"]["units"]["target"]["name"]["text_format"] = ""
	--E.db["unitframe"]["units"]["target"]["name"]["text_format"] = "[namecolor][class]"
	E.db["unitframe"]["units"]["target"]["customTexts"]["lvlName"]["text_format"] = "[difficultycolor][level] [classification] [namecolor][name:medium]"
	
	--targettarget
	E.db["unitframe"]["units"]["targettarget"]["name"]["text_format"] = ""
	--E.db["unitframe"]["units"]["targettarget"]["name"]["text_format"] = "[namecolor][class]"
	E.db["unitframe"]["units"]["targettarget"]["customTexts"]["name1"]["text_format"] = "[namecolor][name:medium]"
	
	--focus
	E.db["unitframe"]["units"]["focus"]["name"]["text_format"] = ""
	--E.db["unitframe"]["units"]["focus"]["name"]["text_format"] = "[namecolor][class]"
	E.db["unitframe"]["units"]["focus"]["customTexts"]["lvlName"]["text_format"] = "[difficultycolor][level] [classification] [namecolor][name:medium]"
	
	--focustarget
	E.db["unitframe"]["units"]["focustarget"]["name"]["text_format"] = ""
	--E.db["unitframe"]["units"]["focustarget"]["name"]["text_format"] = "[namecolor][class]"
	E.db["unitframe"]["units"]["focustarget"]["customTexts"]["name1"]["text_format"] = "[namecolor][name:medium]"
	
	--party
	--E.db["unitframe"]["units"]["party"]["name"]["text_format"] = ""
	E.db["unitframe"]["units"]["party"]["name"]["text_format"] = "[namecolor][name:short]"
	
	--raid
	--E.db["unitframe"]["units"]["raid"]["name"]["text_format"] = ""
	E.db["unitframe"]["units"]["raid"]["name"]["text_format"] = "[namecolor][name:short]"
	
	--raid40
	--E.db["unitframe"]["units"]["raid40"]["name"]["text_format"] = ""
	E.db["unitframe"]["units"]["raid40"]["name"]["text_format"] = "[namecolor][name:short]"
	
	--pettarget
	E.db["unitframe"]["units"]["pettarget"]["name"]["text_format"] = ""
	E.db["unitframe"]["units"]["pettarget"]["customTexts"]["name1"]["text_format"] = "[namecolor][name:short]"

	E:UpdateAll(true)
	E:StaticPopup_Show("PRIVATE_RL")
end

local function GetOptions()
	E.Options.args.myprofile = {
		order = 50,
		name = "My profiles",
		type = 'group',
		args = {
			button = {
				order = 1,
				name = "myUI",
				type = 'execute',
				func = function() myUI() end,
			},
			button2 = {
				order = 2,
				name = "noname",
				type = 'execute',
				func = function() noname() end,
			},
			button3 = {
				order = 3,
				name = "return name",
				type = 'execute',
				func = function() return_name() end,
			},
		},
	}
end

function M:Initialize()
	EP:RegisterPlugin(addon, GetOptions)
end

E:RegisterModule(M:GetName())